networks:
  vaultroom:
    driver: bridge

services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - vaultroom_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_user -d local_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - "vaultroom"

  database-manager:
    image: "dpage/pgadmin4:9.13.0"
    env_file:
      - .env.development
    ports:
      - "80:80"
    networks:
      - "vaultroom"

  server:
    container_name: "kotlin-spring-boot"
    build:
      context: "./server"
      target: development
      network: host
    env_file:
      - .env.development
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/build
      - vaultroom_gradle_cache:/app/.gradle
    depends_on:
      database:
        condition: service_healthy
    networks:
      - "vaultroom"

volumes:
  vaultroom_pg_data:
  vaultroom_gradle_cache:
