CREATE TABLE product_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE register_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE vaults (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    product_quantity INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMPTZ DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    quantity INT DEFAULT 0,
    total_price DECIMAL(12, 2) DEFAULT 0.00,
    price_by_unit DECIMAL(12, 2) DEFAULT 0.00,
    vault_id INT NOT NULL REFERENCES vaults(id) ON DELETE CASCADE,
    type_id INT NOT NULL REFERENCES product_types(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMPTZ DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE registers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desc_register VARCHAR(255) NOT NULL,
    vault_id INT REFERENCES vaults(id) ON DELETE SET NULL,
    product_id INT REFERENCES products(id) ON DELETE SET NULL,
    register_type_id INT REFERENCES register_types(id),
    created_at TIMESTAMPTZ DEFAULT (now() AT TIME ZONE 'utc')
);

-- Seed Data
INSERT INTO product_types (id, name) VALUES
(1, 'Alimentos Secos'),
(2, 'Hortifruti'),
(3, 'Congelados e Carnes'),
(4, 'Laticinios e Ovos'),
(5, 'Bebidas'),
(6, 'Higiene e Limpeza'),
(7, 'Eletronicos e Gadgets'),
(8, 'Papelaria'),
(9, 'Ferramentas');

INSERT INTO register_types (id, slug, name) VALUES
(1, 'add', 'Adicionar'),
(2, 'remove', 'Remover'),
(3, 'change_quantity', 'Corrigir quantity'),
(4, 'change_product', 'Corrigir produto');
