ALTER TABLE product_types
ALTER COLUMN id TYPE BIGINT;

ALTER TABLE register_types
ALTER COLUMN id TYPE BIGINT;

ALTER TABLE vaults
ALTER COLUMN id TYPE BIGINT;

ALTER TABLE products
ALTER COLUMN id TYPE BIGINT,
ALTER COLUMN vault_id TYPE BIGINT,
ALTER COLUMN type_id TYPE BIGINT;

ALTER TABLE registers
ALTER COLUMN id TYPE BIGINT,
ALTER COLUMN product_id TYPE BIGINT,
ALTER COLUMN register_type_id TYPE BIGINT;

